#if !canImport(ObjectiveC)
import XCTest

extension ObserverTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObserverTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ObserverTests.__allTests__ObserverTests),
    ]
}
#endif
