#if !canImport(ObjectiveC)
import XCTest

extension HawkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HawkTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HawkTests.__allTests__HawkTests),
    ]
}
#endif
